### ISSUE TITLE
problem when install flownet2

### ISSUE THREAD

**Issue by Pixie8888** [wanghao9610/flownet2-pytorch-module#3]
Hi,
Thanks for providing flownet2 module.
when I run "sh tools/install.sh", I encountered this problem:
./src/channelnorm_kernel.cu:3:10: fatal error: ATen/cuda/CUDAContext.h: No such file or directory
 #include <ATen/cuda/CUDAContext.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
Any idea how to solve it?

**Comment by wanghao9610** [comment]
Sorry to give a response so late 😄 , hope you have fixed this issue.
This issue may cause by your cuda installation error, you may need to check whether your cuda was installed correctly.
